### ISSUE TITLE
Question on command_line.py

### ISSUE THREAD

**Issue by danielhanbitlee** [Satalia/production-data-science#20]
I have a question on command_line.py. I believe I followed all the steps in the tutorial and entered the following command:

`titanic_analysis --filename exploration/data/titanic.csv`

When I enter this command, I get the following message:

`titanic_analysis: command not found`

It says in the [instructions ](https://github.com/Satalia/production-data-science/tree/master/tutorial/e-iterate_to_product)that the "virtual environment `titanic` has to be active to run this command." How do I activate the `titanic` virtual environment? I have the `titanic_datascience` virtual environment active as described in the previous parts of the tutorial. I have the `titanic` package installed. But I don't know how to activate the `titanic` virtual environment. Or, could some other issue be causing the `titanic_analysis: command not found`?

Any help would be appreciated!

**Comment by FilippoBovo** [comment]
Hi Daniel,

Thanks for your question. Did you add the entry point for the command in `setup.py`?

```python
    entry_points='''
        [console_scripts]
        titanic_analysis=titanic.command_line:titanic_analysis
    '''
```

If it still does not work, reinstall the `titanic` package.
```shell
pip uninstall titanic
cd path/to/titanic/folder
pip install -e .
```
Then, try to run the command again.

Let me know if this solved the problem.

**Comment by danielhanbitlee** [comment]
It worked! Thank you!
