### ISSUE TITLE
b-collaborate: clarity

### ISSUE THREAD

**Issue by mhbw** [Satalia/production-data-science#25]
thanks for this tutorial, appreciate the thought and effort behind it.

couple things that failed for me due to clarity items:

tutorial doesn't say where to start so I stayed in virtualenv, where pip freeze doesn't work. might note where you intend folks to start this part of the tutorial.

secondly: for the install_requires part, I'm not sure what's intended there, I manually wrote it in via nano, but running that code in a bash shell fails.

**Comment by FilippoBovo** [comment]
Hi. You're welcome.

Thank you for your comments.

Regarding your first comment, in part B, you are supposed to run `pip freeze` with the virtual environment active. I am not sure why it did not work for you.

Regarding your second comment, `install_requires` is a list of packages that are installed when installing the Python package created in the tutorial. You may find more information at [this link](https://packaging.python.org/discussions/install-requires-vs-requirements/).
